from selenium import webdriver
import copy
from datetime import datetime
import time
import pyautogui 
import os

class clsCMTLS():

    def __init__(self, url="", strDwnldPath="C:\\Users\\All Users\\tmpDownloads\\TJMS\\"):
        self.url = url
        self.strDwnldPath = strDwnldPath
        pass



    def GetAllData(self):

        arCedencia = []
        arRevoga = []
        
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2018/345/3442/lei-ordinaria-n-3442-2018-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-unir-industria-e-comercio-de-produtos-de-higiene-ltda-epp-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2018/342/3419/lei-ordinaria-n-3419-2018-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-cervejaria-cidade-imperial-petropolis-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2016/308/3072/lei-ordinaria-n-3072-2016-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-transcofer-industria-comercio-e-transportes-ltda-epp-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2015/304/3037/lei-ordinaria-n-3037-2015-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-gep-industria-e-comercio-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2015/299/2981/lei-ordinaria-n-2981-2015-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-ifc-industria-e-comercio-de-condutores-eletricos-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2015/298/2980/lei-ordinaria-n-2980-2015-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-albacolino-3r-transformacao-de-reciclagens-ltda-me-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2015/296/2953/lei-ordinaria-n-2953-2015-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-orestes-da-silva-carvalheiro-junior-me-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2015/295/2949/lei-ordinaria-n-2949-2015-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-nit-fiacao-e-comercio-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2015/291/2908/lei-ordinaria-n-2908-2015-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-d-v-da-silva-me-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2014/283/2823/lei-ordinaria-n-2823-2014-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-jp-comercio-de-embalagens-ltda-me-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2013/274/2736/lei-ordinaria-n-2736-2013-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-linhas-bonfio-sa-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2013/274/2733/lei-ordinaria-n-2733-2013-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-caaete-comercio-de-higiene-e-beleza-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2013/268/2679/lei-ordinaria-n-2679-2013-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-fatex-industria-comercio-importacao-exportacao-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2012/268/2674/lei-ordinaria-n-2674-2012-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-coletti-produtos-siderurgicos-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2012/268/2673/lei-ordinaria-n-2673-2012-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-alpino-fibras-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2012/267/2666/lei-ordinaria-n-2666-2012-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-rfr-comercio-e-servicos-de-usinagem-me-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2012/267/2665/lei-ordinaria-n-2665-2012-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-industria-e-comercio-de-artefatos-de-cimento-pinho-eireli-epp-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2011/250/2499/lei-ordinaria-n-2499-2011-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-areas-a-empresa-oliveira-lopes-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2011/250/2493/lei-ordinaria-n-2493-2011-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-areas-a-empresa-brascopper-cbc-brasileira-de-condutores-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2011/250/2492/lei-ordinaria-n-2492-2011-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-metalfrio-solutions-sa-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2010/248/2471/lei-ordinaria-n-2471-2010-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-linhas-nice-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2012/264/2634/lei-ordinaria-n-2634-2012-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-casa-cozinha-marmoraria-especializada-me-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2012/263/2623/lei-ordinaria-n-2623-2012-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-moacyr-francisco-teixeira-me-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2012/262/2615/lei-ordinaria-n-2615-2012-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-fabrica-e-comercio-de-gelo-tres-lagoas-ltda-me-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2012/262/2613/lei-ordinaria-n-2613-2012-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-so-pedras-pedras-marmores-e-granitos-ltda-epp-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2012/259/2582/lei-ordinaria-n-2582-2012-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-adair-pereira-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2011/253/2527/lei-ordinaria-n-2527-2011-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-nit-fiacao-e-comercio-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2011/252/2518/lei-ordinaria-n-2518-2011-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-ailson-de-jesus-ferreira-me-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2011/252/2511/lei-ordinaria-n-2511-2011-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-feec-quimica-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2011/251/2508/lei-ordinaria-n-2508-2011-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-neutraliza-producao-florestal-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2011/251/2506/lei-ordinaria-n-2506-2011-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-noromix-concreto-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2011/251/2505/lei-ordinaria-n-2505-2011-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-somopar-industria-e-comercio-de-moveis-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2010/247/2469/lei-ordinaria-n-2469-2010-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-constroluz-mix-concreto-ltda-e-da-outras-providencias?q=DOA%C3%87%C3%83O%2C+%C3%81REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2010/246/2459/lei-ordinaria-n-2459-2010-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-fatex-industria-comercio-importacao-exportacao-ltda-e-da-outras-providencias?q=DOA%C3%87%C3%83O%2C+%C3%81REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2010/246/2454/lei-ordinaria-n-2454-2010-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-mk-quimica-do-brasil-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2010/246/2452/lei-ordinaria-n-2452-2010-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-projardi-industria-comercio-importacao-exportacao-e-servicos-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2010/244/2440/lei-ordinaria-n-2440-2010-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-mj-usinagem-ltda-me-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2010/247/2461/lei-ordinaria-n-2461-2010-autoriza-o-poder-executivo-a-doar-area-ao-estado-de-mato-grosso-do-sul-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2010/244/2435/lei-ordinaria-n-2435-2010-autoriza-o-poder-executivo-a-doar-com-encargos-a-petroleo-brasileiro-s-a-petrobras-area-que-menciona-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2010/243/2427/lei-ordinaria-n-2427-2010-autoriza-o-poder-executivo-a-criar-distrito-industrial-que-menciona-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2009/242/2414/lei-ordinaria-n-2414-2009-autoriza-o-poder-executivo-a-desafetar-e-doar-area-ao-estado-de-mato-grosso-do-sul-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2009/239/2386/lei-ordinaria-n-2386-2009-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-acebras-ferro-e-aco-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2009/239/2382/lei-ordinaria-n-2382-2009-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-stell-wire-metalurgica-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2009/238/2378/lei-ordinaria-n-2378-2009-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-tecnocell-industrial-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2009/237/2367/lei-ordinaria-n-2367-2009-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-braga-comercio-e-industria-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2009/237/2362/lei-ordinaria-n-2362-2009-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-rio-prata-embalagens-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2009/236/2360/lei-ordinaria-n-2360-2009-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-areas-a-embalatec-mato-grosso-do-sul-embalagens-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2009/234/2340/lei-ordinaria-n-2340-2009-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-homy-industria-e-comercio-de-produtos-quimicos-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2008/234/2331/lei-ordinaria-n-2331-2008-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-coletres-industria-e-comercio-e-gestao-ambiental-ltda-me-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2008/230/2297/lei-ordinaria-n-2297-2008-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-tb-industria-e-comercio-de-confeccao-de-roupas-ltda-e-da-outras-providencias?q=DOA%C3%87%C3%83O%2C+%C3%81REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2008/230/2295/lei-ordinaria-n-2295-2008-autoriza-o-poder-executivo-a-doar-area-ao-servico-social-do-transporte-sest-e-servico-nacional-de-aprendizagem-do-transporte-senat-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2008/229/2285/lei-ordinaria-n-2285-2008-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-malaga-industria-e-comercio-de-marmores-e-granitos-ltda-me-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2008/229/2283/lei-ordinaria-n-2283-2008-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-ananda-metais-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2008/228/2275/lei-ordinaria-n-2275-2008-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-dmb-construtora-e-consultoria-tecnica-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2008/227/2266/lei-ordinaria-n-2266-2008-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-central-ms-industria-e-comercio-de-ferro-e-aco-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2008/226/2253/lei-ordinaria-n-2253-2008-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-coexpan-brasil-embalagens-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2008/226/2252/lei-ordinaria-n-2252-2008-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-phyto-cosmeticos-industrial-ltda-e-da-outras-providencias?q=DOA%C3%87%C3%83O%2C+%C3%81REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2007/222/2217/lei-ordinaria-n-2217-2007-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-ifc-industria-e-comercio-de-condutores-eletricos-ltda-e-da-outras-providencias?q=DOA%C3%87%C3%83O%2C+%C3%81REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2007/219/2187/lei-ordinaria-n-2187-2007-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-resimax-plasticos-centro-oeste-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2007/219/2186/lei-ordinaria-n-2186-2007-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-mercopack-embalagens-centro-oeste-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2007/218/2173/lei-ordinaria-n-2173-2007-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-conde-duck-industria-de-meias-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2007/217/2167/lei-ordinaria-n-2167-2007-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-lopes-transportes-e-logistica-industria-e-comercio-ltda-epp-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2007/217/2163/lei-ordinaria-n-2163-2007-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-ao-gremio-social-recreativo-esportivo-e-filantropico-19-de-abril-dos-pracas-bombeiros-e-familiares-de-tres-lagoas-ms-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2013/273/2736/lei-ordinaria-n-2736-2013-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-linhas-bonfio-s-a-e-da-outras-providencias")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2007/214/2138/lei-ordinaria-n-2138-2007-autoriza-o-poder-executivo-a-efetuar-doacao-condicionada-de-area-a-empresa-linhas-bonfio-industria-ltda-e-da-outras-providencias?q=DOA%C3%87%C3%83O%2C+%C3%81REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2003/188/1888/lei-ordinaria-n-1888-2003-autoriza-o-poder-executivo-a-doar-a-linhas-bonfio-industria-ltda-e-da-outras-providencias")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2006/211/2105/lei-ordinaria-n-2105-2006-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-complementar-a-emplal-co-embalagens-plasticas-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2006/209/2089/lei-ordinaria-n-2089-2006-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-kelli-cristina-gama-de-souza-me-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2006/209/2088/lei-ordinaria-n-2088-2006-autoriza-o-poder-executivo-a-desafetar-e-a-ceder-em-comodato-para-posterior-doacao-area-que-identifica-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2006/208/2076/lei-ordinaria-n-2076-2006-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-rcg-tecnologia-eletromecanica-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2006/205/2046/lei-ordinaria-n-2046-2006-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-abzil-industria-e-comercio-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2006/205/2044/lei-ordinaria-n-2044-2006-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-complementar-a-brascopper-cbc-brasileira-de-condutores-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2006/204/2038/lei-ordinaria-n-2038-2006-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-emplal-c-o-embalagens-plasticas-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2006/204/2034/lei-ordinaria-n-2034-2006-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-escala-blocos-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2005/204/2032/lei-ordinaria-n-2032-2005-projeto-de-lei-n-95-de-05-de-dezembro-de-2005-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-central-plast-tanques-para-caminhoes-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2005/203/2021/lei-ordinaria-n-2021-2005-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-feral-metalurgica-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2005/202/2016/lei-ordinaria-n-2016-2005-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-gilscar-industria-e-comercio-de-bordados-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2005/201/2004/lei-ordinaria-n-2004-2005-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-rcg-tecnologia-eletromecanica-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2005/199/1982/lei-ordinaria-n-1982-2005-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-missao-salesiana-de-mato-grosso-e-da-outras-providencias?q=DOA%C3%87%C3%83O%2C+%C3%81REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2005/198/1980/lei-ordinaria-n-1980-2005-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-associacao-de-ensino-e-cultura-de-mato-grosso-do-sul-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2005/198/1978/lei-ordinaria-n-1978-2005-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-fast-import-importacao-industria-e-comercio-de-plasticos-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2005/198/1971/lei-ordinaria-n-1971-2005-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-polimakro-industria-de-plasticos-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2005/197/1970/lei-ordinaria-n-1970-2005-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-empresa-metalfrio-solutions-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2005/197/1966/lei-ordinaria-n-1966-2005-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-deposito-de-tecidos-fatex-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2005/196/1956/lei-ordinaria-n-1956-2005-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-fundicao-tres-lagoas-industria-comercio-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2005/196/1954/lei-ordinaria-n-1954-2005-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-area-a-paulo-emilio-freire-lemos-presidente-prudente-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2005/196/1953/lei-ordinaria-n-1953-2005-autoriza-o-poder-executivo-a-doar-com-encargos-area-a-primo-schincariol-industria-de-cervejas-e-refrigerantes-s-a-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2004/196/1952/lei-ordinaria-n-1952-2004-autoriza-o-poder-executivo-a-efetuar-doacao-com-encargos-de-area-a-irmaos-d-agosto-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2004/196/1951/lei-ordinaria-n-1951-2004-autoriza-o-poder-executivo-a-efetuar-doacao-com-encargos-de-area-a-sultan-industria-e-comercio-de-artefatos-texteis-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2004/195/1950/lei-ordinaria-n-1950-2004-autoriza-o-poder-executivo-a-efetuar-doacao-com-encargos-de-area-a-edvaldo-marcio-vicente-me-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2004/195/1948/lei-ordinaria-n-1948-2004-autoriza-o-poder-executivo-a-efetuar-doacao-com-encargos-de-area-a-jorge-mario-ignatz-me-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2004/195/1946/lei-ordinaria-n-1946-2004-autoriza-o-poder-executivo-a-desafetar-area-que-menciona-e-a-doar-com-encargos-a-area-mencionada-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2004/195/1945/lei-ordinaria-n-1945-2004-autoriza-o-poder-executivo-a-doar-com-condicoes-area-a-associacao-dos-leiteiros-e-embaladores-de-leite-de-rua-de-tres-lagoas-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2004/195/1944/lei-ordinaria-n-1944-2004-autoriza-o-poder-executivo-a-efetuar-doacao-com-encargos-de-area-a-associacao-tres-lagoense-das-revendas-agricolas-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2004/195/1942/lei-ordinaria-n-1942-2004-autoriza-o-poder-executivo-a-efetuar-doacao-com-encargos-de-area-complemantar-a-adar-industria-comercio-importacao-e-exportacao-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2004/195/1941/lei-ordinaria-n-1941-2004-autoriza-o-poder-executivo-a-efetuar-doacao-com-encargos-de-area-a-apiarios-flor-da-acacia-ltda-ms-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2004/194/1937/lei-ordinaria-n-1937-2004-autoriza-o-poder-executivo-a-efetuar-doacao-com-encargos-de-area-a-silotres-industria-e-comercio-de-artefatos-de-ferro-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2004/194/1936/lei-ordinaria-n-1936-2004-autoriza-o-poder-executivo-a-efetuar-doacao-com-encargos-de-area-complementar-a-brascopper-cbc-brasileira-de-condutores-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2004/194/1935/lei-ordinaria-n-1935-2004-autoriza-o-poder-executivo-a-efetuar-doacao-com-encargos-de-area-a-marcia-regina-golfetto-de-oliveira-epp-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2004/193/1924/lei-ordinaria-n-1924-2004-autoriza-o-poder-executivo-a-efetuar-doacao-com-encargos-de-area-a-empresa-cooperlagos-cooperativa-de-producao-e-manufatura-tres-lagoas-ms-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2004/193/1923/lei-ordinaria-n-1923-2004-autoriza-o-poder-executivo-a-efetuar-doacao-com-encargos-de-area-ao-sindicato-dos-trabalhadores-publicos-em-saude-trabalho-e-previdencia-em-mato-grosso-do-sul-sintsprev-ms-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2004/193/1922/lei-ordinaria-n-1922-2004-autoriza-o-poder-executivo-a-efetuar-doacao-com-encargos-de-area-a-empresa-coprosul-industria-quimica-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2004/193/1921/lei-ordinaria-n-1921-2004-autoriza-o-poder-executivo-a-efetuar-doacao-condicionada-de-area-a-empresa-winder-marques-tolentino-me-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2004/192/1920/lei-ordinaria-n-1920-2004-autoriza-o-poder-executivo-a-efetuar-doacao-condicionada-de-area-a-cooperativa-dos-trabalhadores-brasileiros-cootbras-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2004/192/1919/lei-ordinaria-n-1919-2004-autoriza-o-poder-executivo-a-efetuar-doacao-condicionada-de-area-a-empresa-gilberto-pereira-dos-santos-e-da-outras-providencias?q=DOA%C3%87%C3%83O%2C+%C3%81REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2004/192/1918/lei-ordinaria-n-1918-2004-autoriza-o-poder-executivo-a-efetuar-doacao-com-encargos-de-area-a-empresa-js-florestal-ltda-e-da-outras-providencias?q=DOA%C3%87%C3%83O%2C+%C3%81REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2004/192/1915/lei-ordinaria-n-1915-2004-autoriza-o-poder-executivo-a-efetuar-doacao-condicionada-de-area-a-empresa-gep-industria-e-comercio-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2004/192/1913/lei-ordinaria-n-1913-2004-autoriza-o-poder-executivo-a-efetuar-doacao-com-encargos-de-area-a-empresa-brasil-pet-industria-e-comercio-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2004/191/1910/lei-ordinaria-n-1910-2004-autoriza-o-poder-executivo-a-efetuar-doacao-com-encargos-de-area-a-empresa-fibrasil-industria-e-comercio-ltda-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2003/189/1886/lei-ordinaria-n-1886-2003-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-de-area-que-denomina-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2003/187/1862/lei-ordinaria-n-1862-2003-altera-dispositivos-da-lei-n-1785-02-de-04-de-junho-de-2002-e-da-lei-n-1833-03-de-25-de-marco-de-2003-que-autorizam-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-de-areas-que-denomina-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2003/187/1861/lei-ordinaria-n-1861-2003-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-de-area-que-denomina-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2003/186/1859/lei-ordinaria-n-1859-2003-autoriza-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-de-area-que-denomina-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")
            arCedencia.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2003/186/1851/lei-ordinaria-n-1851-2003-altera-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-de-area-que-denomina-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA")


        ####                                                                REVOGACOES                                                                ####
        arRevoga.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2015/290/2904/lei-ordinaria-n-2904-2015-dispoe-sobre-a-revogacao-das-leis-que-menciona")
        arRevoga.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2018/338/3385/lei-ordinaria-n-3385-2018-dispoe-sobre-a-revogacao-das-leis-que-mencionam")
        arRevoga.append("https://leismunicipais.com.br/a/ms/t/tres-lagoas/lei-ordinaria/2012/263/2635/lei-ordinaria-n-2635-2012-dispoe-sobre-a-revogacao-das-leis-que-menciona")
        print(arCedencia)
        print("#################################################################################################################")
        print("#################################################################################################################")
        print("#################################################################################################################")
        print(arRevoga)
        pass


        for addrr in arCedencia:
            str(addrr)
            


    
        #brave_path = "C:\\Program Files\\BraveSoftware\\Brave-Browser\\Application\\brave.exe"
        #driver_path = "C:\\Program Files (x86)\\Google\\Drive\\chromedriver.exe"
        #chOptions = webdriver.ChromeOptions()
        #chOptions.binary_location = brave_path
        ##chOptions.add_experimental_option("services.sync.prefs.sync.browser.download.manager.showWhenStarting", False)
        ##chOptions.add_experimental_option("pdfjs.disabled", True)
        ##chOptions.add_experimental_option("print.always_print_silent", True)
        ##chOptions.add_experimental_option("print.show_print_progress", False)
        ##chOptions.add_experimental_option("browser.download.show_plugins_in_list",False)
        #prefs = {"download.default_directory" : self.strDwnldPath}
        #chOptions.add_experimental_option("prefs", prefs);
        #path = self.strDwnldPath
        #vBrowser = webdriver.Chrome(executable_path=driver_path, options=chOptions)

        #self.url = "https://leismunicipais.com.br/a2/ms/t/tres-lagoas/lei-ordinaria/2003/186/1851/lei-ordinaria-n-1851-2003-altera-o-poder-executivo-a-ceder-em-comodato-para-posterior-doacao-de-area-que-denomina-e-da-outras-providencias?q=DOA%C7%C3O%2C%20%C1REA"

        #vBrowser.get(self.url)
        #time.sleep(10)
        #vBrowser.execute_script("window.print();")
        #i=random.randint(0,1000)
        #file_name=('name_pdf '+ str(i))
        #print (file_name)
        #pyautogui.typewrite(file_name)
        #pyautogui.click(512,449)
    pass

xp = clsCMTLS("")
xp.GetAllData()